name: Build and Test on Commit

on:
  push:
    branches:
      - master

jobs:
  build:

    name: "${{ matrix.os }} Build"
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]

    steps:

      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100

      - name: Restore dotnet tools
        run: dotnet tool restore
        shell: pwsh

      - name: Execute build script
        run: dotnet script main.csx
        shell: pwsh